<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->text('name');
            $table->text('last_name')->nullable();    
            $table->string('username')->unique();   
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->longText('about')->nullable();
            $table->text('photo')->nullable()->default('no-img.png');
            $table->text('background')->nullable()->default('no-background.png');
            $table->text('role')->nullable()->default('user');
            $table->text('local')->nullable(); 
            $table->text('age')->nullable();           
            $table->text('gender')->nullable(); 
            $table->text('favorite_design')->nullable()->default('#000');     
            $table->integer('views')->nullable()->default(0);
            $table->text('status')->default('Active');
            $table->text('verified')->default('No');
            $table->text('facebook')->nullable();
            $table->text('instagram')->nullable();
            $table->text('pinterest')->nullable();
            $table->text('tiktok')->nullable();
            $table->text('twitter')->nullable();
            $table->text('youtube')->nullable();  
            $table->integer('facebook_id')->nullable();
            $table->integer('google_id')->nullable();
            $table->integer('microsoft_id')->nullable();
            $table->integer('apple_id')->nullable();
            $table->integer('dailymotion_id')->nullable();
            $table->integer('deviantart_id')->nullable();
            $table->integer('dribbble_id')->nullable();
            $table->integer('flattr_id')->nullable();
            $table->integer('flickr_id')->nullable();
            $table->integer('foursquare_id')->nullable();
            $table->integer('github_id')->nullable();
            $table->integer('imgur_id')->nullable();
            $table->integer('instagram_id')->nullable();
            $table->integer('kakao_id')->nullable();
            $table->integer('line_id')->nullable();
            $table->integer('medium_id')->nullable();
            $table->integer('meetup_id')->nullable();
            $table->integer('azure_id')->nullable();
            $table->integer('naver_id')->nullable();
            $table->integer('odnoklassniki_id')->nullable();
            $table->integer('pinterest_id')->nullable();
            $table->integer('pixnet_id')->nullable();
            $table->integer('pushbullet_id')->nullable();
            $table->integer('reddit_id')->nullable();
            $table->integer('snapchat_id')->nullable();
            $table->integer('stackexchange_id')->nullable();
            $table->integer('tumblr_id')->nullable();
            $table->integer('vimeo_id')->nullable();
            $table->integer('vkontakte_id')->nullable();
            $table->integer('weibo_id')->nullable();
            $table->integer('wordpress_id')->nullable();
            $table->integer('yahoo_id')->nullable();
            $table->integer('yammer_id')->nullable();
            $table->integer('yandex_id')->nullable();
            $table->integer('youtube_id')->nullable();
            $table->integer('battlenet_id')->nullable();
            $table->integer('discord_id')->nullable();
            $table->integer('smashcast_id')->nullable();
            $table->integer('steam_id')->nullable();
            $table->integer('twitch_id')->nullable();
            $table->integer('coursera_id')->nullable();
            $table->integer('goodreads_id')->nullable();
            $table->integer('headhunter_id')->nullable();
            $table->integer('stocktwits_id')->nullable();
            $table->integer('xing_id')->nullable();
            $table->integer('asana_id')->nullable();
            $table->integer('aweber_id')->nullable();
            $table->integer('bitly_id')->nullable();
            $table->integer('bitbucket_id')->nullable();
            $table->integer('box_id')->nullable();
            $table->integer('cheddar_id')->nullable();
            $table->integer('constantcontact_id')->nullable();
            $table->integer('digitalocean_id')->nullable();
            $table->integer('disqus_id')->nullable();
            $table->integer('dropbox_id')->nullable();
            $table->integer('envato_id')->nullable();
            $table->integer('etsy_id')->nullable();
            $table->integer('eventbrite_id')->nullable();
            $table->integer('eyeem_id')->nullable();
            $table->integer('harvest_id')->nullable();
            $table->integer('heroku_id')->nullable();
            $table->integer('hubspot_id')->nullable();
            $table->integer('linkedin_id')->nullable();
            $table->integer('mailchimp_id')->nullable();
            $table->integer('mailru_id')->nullable();
            $table->integer('mattermost_id')->nullable();
            $table->integer('podio_id')->nullable();
            $table->integer('quickbooks_id')->nullable();
            $table->integer('readability_id')->nullable();
            $table->integer('SalesForce_id')->nullable();
            $table->integer('sharepoint_id')->nullable();
            $table->integer('shopify_id')->nullable();
            $table->integer('teamleader_id')->nullable();
            $table->integer('teamweek_id')->nullable();
            $table->integer('trello_id')->nullable();
            $table->integer('unsplash_id')->nullable();
            $table->integer('versionone_id')->nullable();
            $table->integer('whmcs_id')->nullable();
            $table->integer('zendesk_id')->nullable();
            $table->integer('zoho_id')->nullable();
            $table->integer('zoom_id')->nullable();
            $table->integer('uclapi_id')->nullable();
            $table->integer('binance_id')->nullable();
            $table->integer('coinbase_id')->nullable();
            $table->integer('gumroad_id')->nullable();
            $table->integer('mollie_id')->nullable();
            $table->integer('patreon_id')->nullable();
            $table->integer('paypal_id')->nullable();
            $table->integer('redbooth_id')->nullable();
            $table->integer('stripe_id')->nullable();
            $table->integer('venmo_id')->nullable();
            $table->integer('deezer_id')->nullable();
            $table->integer('discogs_id')->nullable();
            $table->integer('mixcloud_id')->nullable();
            $table->integer('soundcloud_id')->nullable();
            $table->integer('spotify_id')->nullable();
            $table->integer('admitad_id')->nullable();
            $table->integer('angellist_id')->nullable();
            $table->integer('douban_id')->nullable();
            $table->integer('fablabs_id')->nullable();
            $table->integer('fitbit_id')->nullable();
            $table->integer('flexkids_id')->nullable();
            $table->integer('strava_id')->nullable();
            $table->integer('trakt_id')->nullable();
            $table->integer('tvshowtime_id')->nullable();
            $table->integer('uber_id')->nullable();  
            $table->text('getIP')->nullable();   
            $table->text('getCity')->nullable();            
            $table->text('getRegion')->nullable();
            $table->text('getRegionCode')->nullable();   
            $table->text('getCountry')->nullable();            
            $table->text('getCountryCode')->nullable();
            $table->text('getContinent')->nullable();   
            $table->text('getContinentCode')->nullable();            
            $table->text('getPostalCode')->nullable();
            $table->text('getLatitude')->nullable();   
            $table->text('getLongitude')->nullable();            
            $table->text('getCurrencyCode')->nullable();
            $table->text('getCurrencySymbol')->nullable();   
            $table->text('getCurrencyExchangeRate')->nullable();            
            $table->text('getLocation')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
